services:
  postgres:
    image: postgres:16
    container_name: qr-webapp-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crab
      POSTGRES_PASSWORD: shellandfish
      POSTGRES_DB: qr_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crab"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
    driver: local
    name: qr-webapp-postgres-data
